### PR TITLE
Multithreading

### PR DESCRIPTION
**Pull request by MrMackan**

### CODE REVIEW

**Review by MrMackan — COMMENTED** [review]
Looks good to me

**Review by portersky — COMMENTED** [review]
The multithreading needs more work for later.

**Review by MrMackan — COMMENTED** [review]
ok

**Review by portersky — APPROVED** [review]
@MrMackan needs to work on the worker code so that we can scale to any amount of threads.

**Comment by MrMackan** [comment]
2 threaded mandelbrot working

**Pull request merged**
